services:
  backend:
    build: .
    ports:
      - "3001:3001"
    command: npm run dev_docker
    volumes:
      - "./src:/app/src:ro"
    depends_on:
      - redis
  
  redis:
    image: redis/redis-stack-server:latest
    ports: 
      - "6371:6379" #! Since there will be more apps with redis, I added a last digit that will increase based on the age of the app.
    
  test: 
    build: .
    command: npm run test
    depends_on:
      - redis
