services:
  backend:
    build: .
    ports:
      - "3001:3001"
    command: npm run dev_docker
    volumes:
      - "./src:/app/src:ro"
    depends_on:
      - redis
  
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
    
  test: 
    build: .
    command: npm run test
    depends_on:
      - redis
