name: AWS git fetch
on:
  push:
    branches: ['master']

jobs:
  run_in_EC2:
    runs-on: ubuntu-latest
    steps:

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.EC2_HOST}} 
          username: ${{secrets.EC2_USER}}
          key: ${{secrets.EC2_SSH_PRIVATE_KEY}}
          passphrase: ${{ secrets.EC2_SSH_PRIVATE_KEY_PASSPHRASE }}

          script: |
            UNIQUE_APP_NAME="${{ secrets.UNIQUE_APP_NAME }}"  
            REPO_PATH="${{ github.repository }}" 
            DOCKER_PORT="${{ secrets.DOCKER_PORTS }}"
            cd ~/vsCodeMain

            [ -d "$UNIQUE_APP_NAME/.git" ] || git clone git@github.com:$REPO_PATH.git "$UNIQUE_APP_NAME" 
            cd "$UNIQUE_APP_NAME" 
            git fetch origin 
            git merge origin/master

            sudo docker compose down
            sudo docker compose up --build -d



            

